// control-plane/web-ui/src/pages/Dashboard.vue
<template>
  <div style="padding: 24px">
    <a-typography-title :level="3">
      Dashboard
      <a-typography-text
        v-if="projectStore.currentProject"
        type="secondary"
        style="font-size: 14px; margin-left: 12px"
      >
        {{ projectStore.currentProject.name }}
      </a-typography-text>
    </a-typography-title>

    <a-row :gutter="[16, 16]">
      <!-- Active Tasks -->
      <a-col :xs="24" :lg="8">
        <a-card title="活跃任务" size="small">
          <a-empty v-if="activeTasks.length === 0" description="暂无活跃任务" />
          <a-list v-else :data-source="activeTasks" size="small">
            <template #renderItem="{ item }">
              <a-list-item>
                <router-link :to="`/tasks/${item.taskId}`">
                  <a-space>
                    <a-typography-text code>{{
                      item.taskId.slice(0, 8)
                    }}</a-typography-text>
                    <a-tag>{{ item.lastEvent }}</a-tag>
                  </a-space>
                </router-link>
              </a-list-item>
            </template>
          </a-list>
        </a-card>
      </a-col>

      <!-- Agent Activity -->
      <a-col :xs="24" :lg="8">
        <a-card title="Agent 活动" size="small">
          <a-empty v-if="agentEvents.length === 0" description="暂无 Agent 活动" />
          <a-list v-else :data-source="agentEvents" size="small">
            <template #renderItem="{ item }">
              <a-list-item>
                <a-space>
                  <a-tag :color="statusColor(item.type.split('.')[1])">
                    {{ item.type.split(".")[1] }}
                  </a-tag>
                  <a-typography-text type="secondary" style="font-size: 12px">
                    {{ item.agentRunId?.slice(0, 8) }}
                  </a-typography-text>
                  <a-typography-text
                    type="secondary"
                    style="font-size: 11px; margin-left: auto"
                  >
                    {{ formatTime(item.ts) }}
                  </a-typography-text>
                </a-space>
              </a-list-item>
            </template>
          </a-list>
        </a-card>
      </a-col>

      <!-- Pending Approvals -->
      <a-col :xs="24" :lg="8">
        <a-card size="small">
          <template #title>
            待审批
            <a-badge
              :count="approvals.length"
              :number-style="{ backgroundColor: '#3b82f6' }"
              style="margin-left: 8px"
            />
          </template>
          <ApprovalPanel :approvals="approvals" @resolved="loadApprovals" />
        </a-card>
      </a-col>
    </a-row>

    <!-- Event Stream -->
    <a-card title="事件流" size="small" style="margin-top: 16px">
      <a-empty v-if="events.length === 0" description="等待事件..." />
      <div v-else style="max-height: 260px; overflow-y: auto">
        <a-table
          :data-source="events.slice(0, 50)"
          :columns="eventColumns"
          :pagination="false"
          size="small"
          row-key="id"
        />
      </div>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue";
import { useRealtimeStore } from "../stores/realtime";
import { useProjectStore } from "../stores/project";
import { listApprovals } from "../lib/api";

const realtimeStore = useRealtimeStore();
const projectStore = useProjectStore();
const approvals = ref<unknown[]>([]);

const events = computed(() => {
  if (!projectStore.currentProjectId) return [];
  return realtimeStore.events.filter((event) => event.projectId === projectStore.currentProjectId);
});

async function loadApprovals() {
  try {
    approvals.value = (await listApprovals("pending")) as unknown[];
  } catch {
    approvals.value = [];
  }
}

onMounted(async () => {
  if (projectStore.projects.length === 0) {
    await projectStore.loadProjects();
  }
  await loadApprovals();
});

const activeTasks = computed(() => {
  const map = new Map<
    string,
    { taskId: string; lastEvent: string; lastUpdate: string }
  >();
  for (const e of events.value) {
    if (
      (e.type === "task.created" || e.type === "task.node.updated") &&
      e.taskId &&
      !map.has(e.taskId)
    ) {
      map.set(e.taskId, {
        taskId: e.taskId,
        lastEvent: e.type,
        lastUpdate: e.ts,
      });
    }
  }
  return Array.from(map.values());
});

const agentEvents = computed(() =>
  events.value.filter((e) => e.type.startsWith("agent.")).slice(0, 10),
);

const eventColumns = [
  {
    title: "时间",
    dataIndex: "ts",
    width: 100,
    customRender: ({ text }: { text: string }) => formatTime(text),
  },
  { title: "类型", dataIndex: "type", width: 180 },
  {
    title: "数据",
    dataIndex: "data",
    ellipsis: true,
    customRender: ({ text }: { text: Record<string, unknown> }) =>
      JSON.stringify(text).slice(0, 100),
  },
];

function formatTime(ts: string) {
  return new Date(ts).toLocaleTimeString();
}

function statusColor(status: string) {
  const map: Record<string, string> = {
    started: "blue",
    running: "blue",
    paused: "orange",
    completed: "green",
    failed: "red",
    stopped: "default",
  };
  return map[status] || "default";
}
</script>

// control-plane/web-ui/src/pages/Dashboard.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useRealtimeStore } from "../stores/realtime";
import { listApprovals } from "../lib/api";
import { ApprovalPanel } from "../components/ApprovalPanel";

export function Dashboard() {
  const events = useRealtimeStore((s) => s.events);
  const [approvals, setApprovals] = useState<unknown[]>([]);

  useEffect(() => {
    listApprovals("pending").then((data) => setApprovals(data as unknown[])).catch(() => {});
  }, []);

  // Derive active tasks from events
  const activeTasks = events
    .filter((e) => e.type === "task.created" || e.type === "task.node.updated")
    .reduce(
      (acc, e) => {
        if (e.taskId && !acc.has(e.taskId)) {
          acc.set(e.taskId, {
            taskId: e.taskId,
            lastEvent: e.type,
            lastUpdate: e.ts,
          });
        }
        return acc;
      },
      new Map<string, { taskId: string; lastEvent: string; lastUpdate: string }>(),
    );

  // Recent agent events
  const agentEvents = events
    .filter((e) => e.type.startsWith("agent."))
    .slice(0, 10);

  return (
    <div className="p-6 space-y-6">
      <h2 className="text-2xl font-bold">Dashboard</h2>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Active Tasks */}
        <div className="bg-slate-900 rounded-xl border border-slate-800 p-4">
          <h3 className="text-sm font-medium text-slate-400 mb-3">Active Tasks</h3>
          {activeTasks.size === 0 ? (
            <p className="text-slate-600 text-sm">No active tasks</p>
          ) : (
            <ul className="space-y-2">
              {Array.from(activeTasks.values()).map((task) => (
                <li key={task.taskId}>
                  <Link
                    to={`/tasks/${task.taskId}`}
                    className="block px-3 py-2 bg-slate-800 rounded-lg hover:bg-slate-700 transition-colors"
                  >
                    <span className="text-sm text-blue-400 font-mono">
                      {task.taskId.slice(0, 8)}...
                    </span>
                    <span className="text-xs text-slate-500 ml-2">{task.lastEvent}</span>
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Agent Activity */}
        <div className="bg-slate-900 rounded-xl border border-slate-800 p-4">
          <h3 className="text-sm font-medium text-slate-400 mb-3">Agent Activity</h3>
          {agentEvents.length === 0 ? (
            <p className="text-slate-600 text-sm">No recent agent activity</p>
          ) : (
            <ul className="space-y-2">
              {agentEvents.map((event) => (
                <li key={event.id} className="flex items-center gap-2 text-sm">
                  <span className={`badge-${event.type.split(".")[1]} px-2 py-0.5 rounded text-xs`}>
                    {event.type.split(".")[1]}
                  </span>
                  <span className="text-slate-400 font-mono text-xs">
                    {event.agentRunId?.slice(0, 8)}
                  </span>
                  <span className="text-slate-600 text-xs ml-auto">
                    {new Date(event.ts).toLocaleTimeString()}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Pending Approvals */}
        <div className="bg-slate-900 rounded-xl border border-slate-800 p-4">
          <h3 className="text-sm font-medium text-slate-400 mb-3">
            Pending Approvals ({Array.isArray(approvals) ? approvals.length : 0})
          </h3>
          <ApprovalPanel approvals={Array.isArray(approvals) ? approvals : []} />
        </div>
      </div>

      {/* Event Stream */}
      <div className="bg-slate-900 rounded-xl border border-slate-800 p-4">
        <h3 className="text-sm font-medium text-slate-400 mb-3">Event Stream</h3>
        <div className="max-h-64 overflow-y-auto space-y-1">
          {events.slice(0, 50).map((event) => (
            <div key={event.id} className="flex items-center gap-3 text-xs py-1 border-b border-slate-800/50">
              <span className="text-slate-600 w-20 shrink-0">
                {new Date(event.ts).toLocaleTimeString()}
              </span>
              <span className="text-blue-400 w-40 shrink-0 font-mono">{event.type}</span>
              <span className="text-slate-500 truncate">
                {JSON.stringify(event.data).slice(0, 100)}
              </span>
            </div>
          ))}
          {events.length === 0 && (
            <p className="text-slate-600 text-sm">Waiting for events...</p>
          )}
        </div>
      </div>
    </div>
  );
}
