// control-plane/web-ui/src/components/AgentConsole.tsx
import { useState } from "react";
import { pauseAgent, resumeAgent, injectGuidance, terminateAgent } from "../lib/api";

interface AgentConsoleProps {
  agentRunId: string;
  agentType: string;
  status: string;
}

export function AgentConsole({ agentRunId, agentType, status }: AgentConsoleProps) {
  const [guidance, setGuidance] = useState("");
  const [loading, setLoading] = useState(false);

  const handleAction = async (action: () => Promise<unknown>) => {
    setLoading(true);
    try {
      await action();
    } catch {
      // Error handling
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="border border-slate-700 rounded-lg p-3">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-2">
          <span className="text-sm font-medium">{agentType}</span>
          <span className="text-xs font-mono text-slate-500">{agentRunId.slice(0, 8)}</span>
        </div>
        <span className={`badge-${status} px-2 py-0.5 rounded text-xs`}>{status}</span>
      </div>

      {/* Control buttons */}
      <div className="flex gap-2 mb-2">
        {status === "running" && (
          <button
            onClick={() => handleAction(() => pauseAgent(agentRunId))}
            disabled={loading}
            className="px-3 py-1 text-xs bg-amber-600/20 text-amber-400 border border-amber-600/30 rounded hover:bg-amber-600/30 disabled:opacity-50"
          >
            Pause
          </button>
        )}
        {status === "paused" && (
          <button
            onClick={() => handleAction(() => resumeAgent(agentRunId))}
            disabled={loading}
            className="px-3 py-1 text-xs bg-green-600/20 text-green-400 border border-green-600/30 rounded hover:bg-green-600/30 disabled:opacity-50"
          >
            Resume
          </button>
        )}
        {(status === "running" || status === "paused") && (
          <button
            onClick={() => handleAction(() => terminateAgent(agentRunId))}
            disabled={loading}
            className="px-3 py-1 text-xs bg-red-600/20 text-red-400 border border-red-600/30 rounded hover:bg-red-600/30 disabled:opacity-50"
          >
            Terminate
          </button>
        )}
      </div>

      {/* Guidance input (only when paused) */}
      {status === "paused" && (
        <div className="flex gap-2">
          <input
            type="text"
            value={guidance}
            onChange={(e) => setGuidance(e.target.value)}
            placeholder="Inject guidance..."
            className="flex-1 px-2 py-1 text-xs bg-slate-800 border border-slate-700 rounded text-slate-200 focus:outline-none focus:border-blue-500"
          />
          <button
            onClick={() => {
              if (guidance.trim()) {
                handleAction(() => injectGuidance(agentRunId, guidance));
                setGuidance("");
              }
            }}
            disabled={loading || !guidance.trim()}
            className="px-3 py-1 text-xs bg-blue-600/20 text-blue-400 border border-blue-600/30 rounded hover:bg-blue-600/30 disabled:opacity-50"
          >
            Send
          </button>
        </div>
      )}
    </div>
  );
}

// control-plane/web-ui/src/components/AgentConsole.vue
<template>
  <a-card size="small" :bordered="true">
    <template #title>
      <a-flex align="center" :gap="8">
        <span>{{ agentType }}</span>
        <a-typography-text code style="font-size: 11px">{{
          agentRunId.slice(0, 8)
        }}</a-typography-text>
        <a-tag :color="statusColor">{{ status }}</a-tag>
      </a-flex>
    </template>

    <!-- Control buttons -->
    <a-space style="margin-bottom: 8px">
      <a-button
        v-if="status === 'running'"
        size="small"
        @click="handleAction(() => pauseAgent(agentRunId))"
        :loading="loading"
      >
        <template #icon><PauseCircleOutlined /></template>
        暂停
      </a-button>
      <a-button
        v-if="status === 'paused'"
        size="small"
        type="primary"
        @click="handleAction(() => resumeAgent(agentRunId))"
        :loading="loading"
      >
        <template #icon><PlayCircleOutlined /></template>
        恢复
      </a-button>
      <a-popconfirm
        v-if="status === 'running' || status === 'paused'"
        title="确定终止此 Agent？"
        @confirm="handleAction(() => terminateAgent(agentRunId))"
      >
        <a-button size="small" danger :loading="loading">
          <template #icon><StopOutlined /></template>
          终止
        </a-button>
      </a-popconfirm>
    </a-space>

    <!-- Guidance input (only when paused) -->
    <a-input-search
      v-if="status === 'paused'"
      v-model:value="guidance"
      placeholder="注入指令..."
      enter-button="发送"
      size="small"
      :loading="loading"
      @search="sendGuidance"
    />
  </a-card>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import {
  PauseCircleOutlined,
  PlayCircleOutlined,
  StopOutlined,
} from "@ant-design/icons-vue";
import { pauseAgent, resumeAgent, injectGuidance, terminateAgent } from "@/lib/api";

const props = defineProps<{
  agentRunId: string;
  agentType: string;
  status: string;
}>();

const guidance = ref("");
const loading = ref(false);

const statusColor = computed(() => {
  const map: Record<string, string> = {
    running: "blue",
    paused: "orange",
    completed: "green",
    failed: "red",
    stopped: "default",
  };
  return map[props.status] || "default";
});

async function handleAction(action: () => Promise<unknown>) {
  loading.value = true;
  try {
    await action();
  } catch {
    // Error handling
  } finally {
    loading.value = false;
  }
}

async function sendGuidance() {
  if (!guidance.value.trim()) return;
  await handleAction(() => injectGuidance(props.agentRunId, guidance.value));
  guidance.value = "";
}
</script>
